-- BattleFit Supabase Schema
-- This script defines the database structure for the BattleFit application.

-- ----------------------------
-- Extensions
-- ----------------------------
-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ----------------------------
-- Types
-- ----------------------------
-- Custom ENUM types for challenges and rankings
CREATE TYPE challenge_type AS ENUM ('daily', 'weekly');
CREATE TYPE ranking_period AS ENUM ('daily', 'weekly');

-- ----------------------------
-- Table structure for users_profile
-- ----------------------------
-- Stores public user data and RPG stats.
CREATE TABLE
  public.users_profile (
    id UUID NOT NULL DEFAULT uuid_generate_v4 () PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE UNIQUE,
    username TEXT NOT NULL UNIQUE,
    level INT NOT NULL DEFAULT 1,
    exp INT NOT NULL DEFAULT 0,
    strength INT NOT NULL DEFAULT 1,
    stamina INT NOT NULL DEFAULT 1,
    speed INT NOT NULL DEFAULT 1,
    energy INT NOT NULL DEFAULT 100,
    coins INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone ('utc'::TEXT, NOW()) NOT NULL
  );

-- Add comments to the table and columns
COMMENT ON TABLE public.users_profile IS 'Stores public user data and RPG stats.';
COMMENT ON COLUMN public.users_profile.user_id IS 'Foreign key to the authenticated user.';

-- Create an index on the user_id for faster lookups.
CREATE INDEX idx_users_profile_user_id ON public.users_profile (user_id);

-- ----------------------------
-- Function to create a new user profile on signup
-- ----------------------------
-- This function is triggered when a new user signs up via Supabase Auth.
CREATE OR REPLACE FUNCTION public.handle_new_user () RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users_profile (user_id, username)
  VALUES (new.id, new.raw_user_meta_data->>'username');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ----------------------------
-- Trigger to call the function on new user creation
-- ----------------------------
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE PROCEDURE public.handle_new_user ();

-- ----------------------------
-- Table structure for daily_activity
-- ----------------------------
-- Tracks daily synchronized health data for each user.
CREATE TABLE
  public.daily_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    date DATE NOT NULL,
    steps INT NOT NULL DEFAULT 0,
    calories INT NOT NULL DEFAULT 0,
    active_minutes INT NOT NULL DEFAULT 0,
    distance DOUBLE PRECISION NOT NULL DEFAULT 0,
    exp_gained INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone ('utc'::TEXT, NOW()) NOT NULL,
    UNIQUE (user_id, date)
  );

COMMENT ON TABLE public.daily_activity IS 'Tracks daily synchronized health data for each user.';
CREATE INDEX idx_daily_activity_user_date ON public.daily_activity (user_id, date);

-- ----------------------------
-- Table structure for challenges
-- ----------------------------
-- Defines all available challenges in the game.
CREATE TABLE
  public.challenges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    type challenge_type NOT NULL,
    goal INT NOT NULL,
    reward_exp INT NOT NULL,
    reward_coins INT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
  );

COMMENT ON TABLE public.challenges IS 'Defines all available challenges in the game.';

-- ----------------------------
-- Table structure for user_challenges
-- ----------------------------
-- Tracks the progress of users on specific challenges.
CREATE TABLE
  public.user_challenges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    challenge_id BIGINT NOT NULL REFERENCES public.challenges (id) ON DELETE CASCADE,
    progress INT NOT NULL DEFAULT 0,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    assigned_date DATE NOT NULL DEFAULT CURRENT_DATE,
    completed_at TIMESTAMP WITH TIME ZONE,
    UNIQUE (user_id, challenge_id, assigned_date)
  );

COMMENT ON TABLE public.user_challenges IS 'Tracks the progress of users on specific challenges.';
CREATE INDEX idx_user_challenges_user_id ON public.user_challenges (user_id);

-- ----------------------------
-- Table structure for ranking
-- ----------------------------
-- Stores ranking data for users.
CREATE TABLE
  public.ranking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    period ranking_period NOT NULL,
    score INT NOT NULL,
    position INT,
    rank_date DATE NOT NULL
  );

COMMENT ON TABLE public.ranking IS 'Stores ranking data. The position is calculated periodically.';
CREATE INDEX idx_ranking_period_date_score ON public.ranking (period, rank_date, score DESC);
CREATE INDEX idx_ranking_user_id ON public.ranking (user_id);
