type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
}

type Movie @table {
  title: String!
  year: Int!
  createdAt: Timestamp!
  summary: String
  genres: [String]
  runtime: Int
}

type Watch @table {
  user: User!
  movie: Movie!
  createdAt: Timestamp!
  watchDate: Date!
  location: String
}

type Review @table {
  user: User!
  movie: Movie!
  watch: Watch!
  rating: Int!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  text: String
  isPublic: Boolean
  shareId: UUID
}

type MovieList @table {
  user: User!
  name: String!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  description: String
  isPublic: Boolean
}

type MovieListEntry @table {
  movieList: MovieList!
  movie: Movie!
  position: Int!
  note: String
}